const crypto = require('crypto');
const { extractFields } = require('./extract-fields');
const { mapFields } = require('./field-mapping');
const { getAccessToken } = require('./docusign-auth');
const { createTemplate } = require('./docusign-template');
const { buildFormSchema, createForm, createWorkflow, attachN8nProjection, createDocumentMapping } = require('./milemarker');

/**
 * Phase 1 — the only part of the pipeline that needs the raw PDF bytes: extract fields,
 * map field names, and create the DocuSign Template. Split out from phase 2 so it can run
 * synchronously in a fast Netlify Function (a real, live-discovered constraint: Netlify
 * Background Function invocations have a payload cap far too small for a multi-MB PDF, so
 * the PDF bytes must never need to travel anywhere past this one call — they arrive with the
 * original request and get used immediately, not re-transmitted).
 *
 * @returns {Promise<{templateId, mappedFields, fieldCount, byType, pdfSha256}>}
 */
async function createTemplateFromPdf({ pdfBytes, documentName, workflowName, docusign: { accountId, apiBase } }) {
  const { fields } = await extractFields(pdfBytes);
  const mappedFields = mapFields(fields);

  const { accessToken } = await getAccessToken();

  const { templateId } = await createTemplate({
    accessToken,
    accountId,
    apiBase,
    pdfBytes,
    documentName,
    mappedFields,
    templateName: workflowName,
  });

  const byType = {};
  for (const f of mappedFields) byType[f.tabType] = (byType[f.tabType] || 0) + 1;

  return {
    templateId,
    mappedFields,
    fieldCount: mappedFields.length,
    byType,
    pdfSha256: crypto.createHash('sha256').update(pdfBytes).digest('hex'),
  };
}

/**
 * Phase 2 — everything after the DocuSign Template exists: create the matching Milemarker
 * Form + Workflow, attach the create-trigger to the shared "Generic Doc Onboarding" n8n
 * workflow (via an existing n8n projection id — no new n8n workflow is created per document),
 * and write the document-identity mapping record that n8n looks up at submit time. None of
 * this needs the PDF bytes, only `mappedFields` (a small JSON array) — small enough that this
 * phase is safe to run as a Background Function job with the rest of phase 2's inputs in its
 * invocation payload directly, no blob/file hand-off needed.
 *
 * Together with phase 1, this makes the new workflow fully live end-to-end with no manual
 * n8n/mapping-record step — the only step still left to a human is placing signature/initial/
 * date tabs (add_field_tab) and publishing the workflow once those are confirmed placed, since
 * an unsignable document shouldn't be submittable yet.
 *
 * @returns {Promise<{formId, workflowId, templateId, fieldCount, byType, n8nAttached, mappingRecordId}>}
 */
async function createWorkflowForTemplate({
  templateId,
  mappedFields,
  fieldCount,
  byType,
  pdfSha256,
  documentName,
  workflowName,
  workflowDescription,
  milemarker: { baseUrl, apiKey, workflowTypeId, workflowCategoryId, workflowAccessLevels, defaultAssignees, icon, n8nProjectionId, onboardedBy },
}) {
  const schema = buildFormSchema(mappedFields);
  const form = await createForm({
    baseUrl,
    apiKey,
    name: workflowName,
    description: `Auto-generated by the PDF onboarding pipeline from "${documentName}". ${mappedFields.length} fields auto-detected from the PDF's own form fields. Paired 1:1 with DocuSign template ${templateId} via matching field-key/tab-label names.`,
    schema,
  });

  const workflow = await createWorkflow({
    baseUrl,
    apiKey,
    name: workflowName,
    description: workflowDescription || `Auto-onboarded via the generic PDF-onboarding pipeline. Submitting this form pre-fills "${documentName}" and sends it for e-signature via DocuSign (template ${templateId}).`,
    icon: icon || 'heroicon-o-document-text',
    formId: form.id,
    workflowTypeId,
    workflowCategoryId,
    workflowAccessLevels,
    defaultAssignees,
  });

  await attachN8nProjection({
    baseUrl,
    apiKey,
    workflowId: workflow.id,
    projectionId: n8nProjectionId,
  });

  const mappingRecord = await createDocumentMapping({
    baseUrl,
    apiKey,
    workflowId: workflow.id,
    templateId,
    pdfSha256,
    documentName,
    onboardedBy: onboardedBy || 'docusign-pdf-onboarder MCP',
    signatureTabsPlaced: false,
  });

  return {
    formId: form.id,
    workflowId: workflow.id,
    templateId,
    fieldCount,
    byType,
    n8nAttached: true,
    mappingRecordId: mappingRecord.id,
    note: 'Workflow created as draft. Add signature/initial/date tabs with add_field_tab, then publish the workflow once confirmed before real client use.',
  };
}

/** Convenience wrapper running both phases back to back — used by test-local.js and anywhere
 * the full pipeline can safely run inline (e.g. a small PDF, or outside Netlify's Function
 * timeout constraints entirely). The live HTTP/MCP entry points do NOT use this — they run
 * phase 1 synchronously and phase 2 as a Background Function job (see lib/onboard-async.js). */
async function onboardPdf({ pdfBytes, documentName, workflowName, workflowDescription, docusign, milemarker }) {
  const phase1 = await createTemplateFromPdf({ pdfBytes, documentName, workflowName, docusign });
  return createWorkflowForTemplate({ ...phase1, documentName, workflowName, workflowDescription, milemarker });
}

module.exports = { onboardPdf, createTemplateFromPdf, createWorkflowForTemplate };
