const crypto = require('crypto');
const { extractFields } = require('./extract-fields');
const { mapFields } = require('./field-mapping');
const { getAccessToken } = require('./docusign-auth');
const { createTemplate } = require('./docusign-template');
const { buildFormSchema, createForm, createWorkflow, attachN8nProjection, createDocumentMapping } = require('./milemarker');

/**
 * The full "onboard this PDF" pipeline: extract fields -> create a DocuSign
 * Template -> create a matching Milemarker Form + Workflow. Does NOT touch
 * the original hand-built DocuSign POC (workflow 54 / form 61 / template
 * 6f6a0cee-...) — every call here creates new records.
 *
 * Config (workflow type/category/access levels/assignees) is passed in
 * rather than hardcoded, since it's tenant- and org-specific — the Netlify
 * function handler supplies Flatiron's defaults, but nothing here assumes
 * a single tenant.
 *
 * Also wires the create-trigger to the shared "Generic Doc Onboarding" n8n workflow (via
 * an existing n8n projection id — no new n8n workflow is created per document) and writes
 * the document-identity mapping record that workflow looks up at submit time. Together
 * with the Milemarker Workflow/Form + DocuSign Template above, this makes the new workflow
 * fully live end-to-end with no manual n8n/mapping-record step — the only step still left
 * to a human is placing signature/initial/date tabs (add_field_tab) and publishing the
 * workflow once those are confirmed placed, since an unsignable document shouldn't be
 * submittable yet.
 *
 * @returns {Promise<{formId, workflowId, templateId, fieldCount, byType, n8nAttached, mappingRecordId}>}
 */
async function onboardPdf({
  pdfBytes,
  documentName,
  workflowName,
  workflowDescription,
  docusign: { accountId, apiBase },
  milemarker: { baseUrl, apiKey, workflowTypeId, workflowCategoryId, workflowAccessLevels, defaultAssignees, icon, n8nProjectionId, onboardedBy },
}) {
  const { fields } = await extractFields(pdfBytes);
  const mappedFields = mapFields(fields);

  const { accessToken } = await getAccessToken();

  const { templateId } = await createTemplate({
    accessToken,
    accountId,
    apiBase,
    pdfBytes,
    documentName,
    mappedFields,
    templateName: workflowName,
  });

  const schema = buildFormSchema(mappedFields);
  const form = await createForm({
    baseUrl,
    apiKey,
    name: workflowName,
    description: `Auto-generated by the PDF onboarding pipeline from "${documentName}". ${mappedFields.length} fields auto-detected from the PDF's own form fields. Paired 1:1 with DocuSign template ${templateId} via matching field-key/tab-label names.`,
    schema,
  });

  const workflow = await createWorkflow({
    baseUrl,
    apiKey,
    name: workflowName,
    description: workflowDescription || `Auto-onboarded via the generic PDF-onboarding pipeline. Submitting this form pre-fills "${documentName}" and sends it for e-signature via DocuSign (template ${templateId}).`,
    icon: icon || 'heroicon-o-document-text',
    formId: form.id,
    workflowTypeId,
    workflowCategoryId,
    workflowAccessLevels,
    defaultAssignees,
  });

  const byType = {};
  for (const f of mappedFields) byType[f.tabType] = (byType[f.tabType] || 0) + 1;

  const pdfSha256 = crypto.createHash('sha256').update(pdfBytes).digest('hex');

  await attachN8nProjection({
    baseUrl,
    apiKey,
    workflowId: workflow.id,
    projectionId: n8nProjectionId,
  });

  const mappingRecord = await createDocumentMapping({
    baseUrl,
    apiKey,
    workflowId: workflow.id,
    templateId,
    pdfSha256,
    documentName,
    onboardedBy: onboardedBy || 'docusign-pdf-onboarder MCP',
    signatureTabsPlaced: false,
  });

  return {
    formId: form.id,
    workflowId: workflow.id,
    templateId,
    fieldCount: mappedFields.length,
    byType,
    n8nAttached: true,
    mappingRecordId: mappingRecord.id,
    note: 'Workflow created as draft. Add signature/initial/date tabs with add_field_tab, then publish the workflow once confirmed before real client use.',
  };
}

module.exports = { onboardPdf };
