const { extractFields } = require('./extract-fields');
const { mapFields } = require('./field-mapping');
const { getAccessToken } = require('./docusign-auth');
const { createTemplate } = require('./docusign-template');
const { buildFormSchema, createForm, createWorkflow } = require('./milemarker');

/**
 * The full "onboard this PDF" pipeline: extract fields -> create a DocuSign
 * Template -> create a matching Milemarker Form + Workflow. Does NOT touch
 * the original hand-built DocuSign POC (workflow 54 / form 61 / template
 * 6f6a0cee-...) — every call here creates new records.
 *
 * Config (workflow type/category/access levels/assignees) is passed in
 * rather than hardcoded, since it's tenant- and org-specific — the Netlify
 * function handler supplies Flatiron's defaults, but nothing here assumes
 * a single tenant.
 *
 * @returns {Promise<{formId, workflowId, templateId, fieldCount, byType}>}
 */
async function onboardPdf({
  pdfBytes,
  documentName,
  workflowName,
  workflowDescription,
  docusign: { accountId, apiBase },
  milemarker: { baseUrl, apiKey, workflowTypeId, workflowCategoryId, workflowAccessLevels, defaultAssignees, icon },
}) {
  const { fields } = await extractFields(pdfBytes);
  const mappedFields = mapFields(fields);

  const { accessToken } = await getAccessToken();

  const { templateId } = await createTemplate({
    accessToken,
    accountId,
    apiBase,
    pdfBytes,
    documentName,
    mappedFields,
    templateName: workflowName,
  });

  const schema = buildFormSchema(mappedFields);
  const form = await createForm({
    baseUrl,
    apiKey,
    name: workflowName,
    description: `Auto-generated by the PDF onboarding pipeline from "${documentName}". ${mappedFields.length} fields auto-detected from the PDF's own form fields. Paired 1:1 with DocuSign template ${templateId} via matching field-key/tab-label names.`,
    schema,
  });

  const workflow = await createWorkflow({
    baseUrl,
    apiKey,
    name: workflowName,
    description: workflowDescription || `Auto-onboarded via the generic PDF-onboarding pipeline. Submitting this form pre-fills "${documentName}" and sends it for e-signature via DocuSign (template ${templateId}).`,
    icon: icon || 'heroicon-o-document-text',
    formId: form.id,
    workflowTypeId,
    workflowCategoryId,
    workflowAccessLevels,
    defaultAssignees,
  });

  const byType = {};
  for (const f of mappedFields) byType[f.tabType] = (byType[f.tabType] || 0) + 1;

  return {
    formId: form.id,
    workflowId: workflow.id,
    templateId,
    fieldCount: mappedFields.length,
    byType,
  };
}

module.exports = { onboardPdf };
